//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace WpfKolekcjaZdjec.Entities
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(HddDirectory))]
    [KnownType(typeof(Pendrive))]
    [KnownType(typeof(CardReader))]
    [KnownType(typeof(ReadOnlyArchive))]
    [KnownType(typeof(DigitalCamera))]
    [KnownType(typeof(Photo))]
    public abstract partial class Archive: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int Id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'Id' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _id = value;
                    OnPropertyChanged("Id");
                }
            }
        }
        private int _id;
    
        [DataMember]
        public string VolumeName
        {
            get { return _volumeName; }
            set
            {
                if (_volumeName != value)
                {
                    _volumeName = value;
                    OnPropertyChanged("VolumeName");
                }
            }
        }
        private string _volumeName;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public Photo Photo
        {
            get { return _photo; }
            set
            {
                if (!ReferenceEquals(_photo, value))
                {
                    var previousValue = _photo;
                    _photo = value;
                    FixupPhoto(previousValue);
                    OnNavigationPropertyChanged("Photo");
                }
            }
        }
        private Photo _photo;
    
        [DataMember]
        public TrackableCollection<Photo> Photo_1
        {
            get
            {
                if (_photo_1 == null)
                {
                    _photo_1 = new TrackableCollection<Photo>();
                    _photo_1.CollectionChanged += FixupPhoto_1;
                }
                return _photo_1;
            }
            set
            {
                if (!ReferenceEquals(_photo_1, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_photo_1 != null)
                    {
                        _photo_1.CollectionChanged -= FixupPhoto_1;
                    }
                    _photo_1 = value;
                    if (_photo_1 != null)
                    {
                        _photo_1.CollectionChanged += FixupPhoto_1;
                    }
                    OnNavigationPropertyChanged("Photo_1");
                }
            }
        }
        private TrackableCollection<Photo> _photo_1;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Photo = null;
            FixupPhotoKeys();
            Photo_1.Clear();
        }

        #endregion
        #region Association Fixup
    
        private void FixupPhoto(Photo previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.Source.Contains(this))
            {
                previousValue.Source.Remove(this);
            }
    
            if (Photo != null)
            {
                if (!Photo.Source.Contains(this))
                {
                    Photo.Source.Add(this);
                }
    
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Photo")
                    && (ChangeTracker.OriginalValues["Photo"] == Photo))
                {
                    ChangeTracker.OriginalValues.Remove("Photo");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Photo", previousValue);
                }
                if (Photo != null && !Photo.ChangeTracker.ChangeTrackingEnabled)
                {
                    Photo.StartTracking();
                }
                FixupPhotoKeys();
            }
        }
    
        private void FixupPhotoKeys()
        {
            const string IdKeyName = "Photo.Id";
    
            if(ChangeTracker.ExtendedProperties.ContainsKey(IdKeyName))
            {
                if(Photo == null ||
                   !Equals(ChangeTracker.ExtendedProperties[IdKeyName], Photo.Id))
                {
                    ChangeTracker.RecordOriginalValue(IdKeyName, ChangeTracker.ExtendedProperties[IdKeyName]);
                }
                ChangeTracker.ExtendedProperties.Remove(IdKeyName);
            }
        }
    
        private void FixupPhoto_1(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (Photo item in e.NewItems)
                {
                    item.Archives = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("Photo_1", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Photo item in e.OldItems)
                {
                    if (ReferenceEquals(item.Archives, this))
                    {
                        item.Archives = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("Photo_1", item);
                    }
                }
            }
        }

        #endregion
    }
}
