//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace WpfKolekcjaZdjec.Entities
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Photo))]
    [KnownType(typeof(Photos2Locations))]
    public partial class Archive: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int ID
        {
            get { return _iD; }
            set
            {
                if (_iD != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'ID' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _iD = value;
                    OnPropertyChanged("ID");
                }
            }
        }
        private int _iD;
    
        [DataMember]
        public string VolumeName
        {
            get { return _volumeName; }
            set
            {
                if (_volumeName != value)
                {
                    _volumeName = value;
                    OnPropertyChanged("VolumeName");
                }
            }
        }
        private string _volumeName;
    
        [DataMember]
        public Nullable<long> Capacity
        {
            get { return _capacity; }
            set
            {
                if (_capacity != value)
                {
                    _capacity = value;
                    OnPropertyChanged("Capacity");
                }
            }
        }
        private Nullable<long> _capacity;
    
        [DataMember]
        public string HddLetter
        {
            get { return _hddLetter; }
            set
            {
                if (_hddLetter != value)
                {
                    _hddLetter = value;
                    OnPropertyChanged("HddLetter");
                }
            }
        }
        private string _hddLetter;
    
        [DataMember]
        public string DeviceID
        {
            get { return _deviceID; }
            set
            {
                if (_deviceID != value)
                {
                    _deviceID = value;
                    OnPropertyChanged("DeviceID");
                }
            }
        }
        private string _deviceID;
    
        [DataMember]
        public Nullable<bool> IsExternal
        {
            get { return _isExternal; }
            set
            {
                if (_isExternal != value)
                {
                    _isExternal = value;
                    OnPropertyChanged("IsExternal");
                }
            }
        }
        private Nullable<bool> _isExternal;
    
        [DataMember]
        public string DiscLetter
        {
            get { return _discLetter; }
            set
            {
                if (_discLetter != value)
                {
                    _discLetter = value;
                    OnPropertyChanged("DiscLetter");
                }
            }
        }
        private string _discLetter;
    
        [DataMember]
        public string DiscType
        {
            get { return _discType; }
            set
            {
                if (_discType != value)
                {
                    _discType = value;
                    OnPropertyChanged("DiscType");
                }
            }
        }
        private string _discType;
    
        [DataMember]
        public string ArchiveType
        {
            get { return _archiveType; }
            set
            {
                if (_archiveType != value)
                {
                    _archiveType = value;
                    OnPropertyChanged("ArchiveType");
                }
            }
        }
        private string _archiveType;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public TrackableCollection<Photo> Photos
        {
            get
            {
                if (_photos == null)
                {
                    _photos = new TrackableCollection<Photo>();
                    _photos.CollectionChanged += FixupPhotos;
                }
                return _photos;
            }
            set
            {
                if (!ReferenceEquals(_photos, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_photos != null)
                    {
                        _photos.CollectionChanged -= FixupPhotos;
                    }
                    _photos = value;
                    if (_photos != null)
                    {
                        _photos.CollectionChanged += FixupPhotos;
                    }
                    OnNavigationPropertyChanged("Photos");
                }
            }
        }
        private TrackableCollection<Photo> _photos;
    
        [DataMember]
        public TrackableCollection<Photos2Locations> Photos2Locations
        {
            get
            {
                if (_photos2Locations == null)
                {
                    _photos2Locations = new TrackableCollection<Photos2Locations>();
                    _photos2Locations.CollectionChanged += FixupPhotos2Locations;
                }
                return _photos2Locations;
            }
            set
            {
                if (!ReferenceEquals(_photos2Locations, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_photos2Locations != null)
                    {
                        _photos2Locations.CollectionChanged -= FixupPhotos2Locations;
                        // This is the principal end in an association that performs cascade deletes.
                        // Remove the cascade delete event handler for any entities in the current collection.
                        foreach (Photos2Locations item in _photos2Locations)
                        {
                            ChangeTracker.ObjectStateChanging -= item.HandleCascadeDelete;
                        }
                    }
                    _photos2Locations = value;
                    if (_photos2Locations != null)
                    {
                        _photos2Locations.CollectionChanged += FixupPhotos2Locations;
                        // This is the principal end in an association that performs cascade deletes.
                        // Add the cascade delete event handler for any entities that are already in the new collection.
                        foreach (Photos2Locations item in _photos2Locations)
                        {
                            ChangeTracker.ObjectStateChanging += item.HandleCascadeDelete;
                        }
                    }
                    OnNavigationPropertyChanged("Photos2Locations");
                }
            }
        }
        private TrackableCollection<Photos2Locations> _photos2Locations;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Photos.Clear();
            Photos2Locations.Clear();
        }

        #endregion
        #region Association Fixup
    
        private void FixupPhotos(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (Photo item in e.NewItems)
                {
                    item.Archive = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("Photos", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Photo item in e.OldItems)
                {
                    if (ReferenceEquals(item.Archive, this))
                    {
                        item.Archive = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("Photos", item);
                    }
                }
            }
        }
    
        private void FixupPhotos2Locations(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (Photos2Locations item in e.NewItems)
                {
                    item.Archive = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("Photos2Locations", item);
                    }
                    // This is the principal end in an association that performs cascade deletes.
                    // Update the event listener to refer to the new dependent.
                    ChangeTracker.ObjectStateChanging += item.HandleCascadeDelete;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Photos2Locations item in e.OldItems)
                {
                    if (ReferenceEquals(item.Archive, this))
                    {
                        item.Archive = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("Photos2Locations", item);
                        // Delete the dependent end of this identifying association. If the current state is Added,
                        // allow the relationship to be changed without causing the dependent to be deleted.
                        if (item.ChangeTracker.State != ObjectState.Added)
                        {
                            item.MarkAsDeleted();
                        }
                    }
                    // This is the principal end in an association that performs cascade deletes.
                    // Remove the previous dependent from the event listener.
                    ChangeTracker.ObjectStateChanging -= item.HandleCascadeDelete;
                }
            }
        }

        #endregion
    }
}
