//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data.Common;
using System.Data.EntityClient;
using System.Data.Metadata.Edm;
using System.Data.Objects.DataClasses;
using System.Data.Objects;
using System.Data;
using System.Diagnostics;
using System.Globalization;
using System.Linq;

namespace WpfKolekcjaZdjec.Entities
{
    public partial class PhotoCollectionDatabaseEntities : ObjectContext
    {
        public const string ConnectionString = "name=PhotoCollectionDatabaseEntities";
        public const string ContainerName = "PhotoCollectionDatabaseEntities";
    
        #region Constructors
    
        public PhotoCollectionDatabaseEntities()
            : base(ConnectionString, ContainerName)
        {
            Initialize();
        }
    
        public PhotoCollectionDatabaseEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            Initialize();
        }
    
        public PhotoCollectionDatabaseEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            Initialize();
        }
    
        private void Initialize()
        {
            // Creating proxies requires the use of the ProxyDataContractResolver and
            // may allow lazy loading which can expand the loaded graph during serialization.
            ContextOptions.ProxyCreationEnabled = false;
            ObjectMaterialized += new ObjectMaterializedEventHandler(HandleObjectMaterialized);
        }
    
        private void HandleObjectMaterialized(object sender, ObjectMaterializedEventArgs e)
        {
            var entity = e.Entity as IObjectWithChangeTracker;
            if (entity != null)
            {
                bool changeTrackingEnabled = entity.ChangeTracker.ChangeTrackingEnabled;
                try
                {
                    entity.MarkAsUnchanged();
                }
                finally
                {
                    entity.ChangeTracker.ChangeTrackingEnabled = changeTrackingEnabled;
                }
                this.StoreReferenceKeyValues(entity);
            }
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<AdditionalAttribute> AdditionalAttributes
        {
            get { return _additionalAttributes  ?? (_additionalAttributes = CreateObjectSet<AdditionalAttribute>("AdditionalAttributes")); }
        }
        private ObjectSet<AdditionalAttribute> _additionalAttributes;
    
        public ObjectSet<Archive> Archives
        {
            get { return _archives  ?? (_archives = CreateObjectSet<Archive>("Archives")); }
        }
        private ObjectSet<Archive> _archives;
    
        public ObjectSet<Attribute> Attributes
        {
            get { return _attributes  ?? (_attributes = CreateObjectSet<Attribute>("Attributes")); }
        }
        private ObjectSet<Attribute> _attributes;
    
        public ObjectSet<ExifAttribute> ExifAttributes
        {
            get { return _exifAttributes  ?? (_exifAttributes = CreateObjectSet<ExifAttribute>("ExifAttributes")); }
        }
        private ObjectSet<ExifAttribute> _exifAttributes;
    
        public ObjectSet<Photo> Photos
        {
            get { return _photos  ?? (_photos = CreateObjectSet<Photo>("Photos")); }
        }
        private ObjectSet<Photo> _photos;
    
        public ObjectSet<ReportsHistory> ReportsHistories
        {
            get { return _reportsHistories  ?? (_reportsHistories = CreateObjectSet<ReportsHistory>("ReportsHistories")); }
        }
        private ObjectSet<ReportsHistory> _reportsHistories;
    
        public ObjectSet<SavedReport> SavedReports
        {
            get { return _savedReports  ?? (_savedReports = CreateObjectSet<SavedReport>("SavedReports")); }
        }
        private ObjectSet<SavedReport> _savedReports;
    
        public ObjectSet<Tag> Tags
        {
            get { return _tags  ?? (_tags = CreateObjectSet<Tag>("Tags")); }
        }
        private ObjectSet<Tag> _tags;

        #endregion
    }
}
