//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace WpfKolekcjaZdjec.Entities
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Photo))]
    [KnownType(typeof(Archive))]
    public partial class Photos2Locations: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int PhotoID
        {
            get { return _photoID; }
            set
            {
                if (_photoID != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'PhotoID' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    if (!IsDeserializing)
                    {
                        if (Photo != null && Photo.ID != value)
                        {
                            Photo = null;
                        }
                    }
                    _photoID = value;
                    OnPropertyChanged("PhotoID");
                }
            }
        }
        private int _photoID;
    
        [DataMember]
        public int LocationID
        {
            get { return _locationID; }
            set
            {
                if (_locationID != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'LocationID' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    if (!IsDeserializing)
                    {
                        if (Archive != null && Archive.ID != value)
                        {
                            Archive = null;
                        }
                    }
                    _locationID = value;
                    OnPropertyChanged("LocationID");
                }
            }
        }
        private int _locationID;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public Photo Photo
        {
            get { return _photo; }
            set
            {
                if (!ReferenceEquals(_photo, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added && value != null)
                    {
                        // This the dependent end of an identifying relationship, so the principal end cannot be changed if it is already set,
                        // otherwise it can only be set to an entity with a primary key that is the same value as the dependent's foreign key.
                        if (PhotoID != value.ID)
                        {
                            throw new InvalidOperationException("The principal end of an identifying relationship can only be changed when the dependent end is in the Added state.");
                        }
                    }
                    var previousValue = _photo;
                    _photo = value;
                    FixupPhoto(previousValue);
                    OnNavigationPropertyChanged("Photo");
                }
            }
        }
        private Photo _photo;
    
        [DataMember]
        public Archive Archive
        {
            get { return _archive; }
            set
            {
                if (!ReferenceEquals(_archive, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added && value != null)
                    {
                        // This the dependent end of an identifying relationship, so the principal end cannot be changed if it is already set,
                        // otherwise it can only be set to an entity with a primary key that is the same value as the dependent's foreign key.
                        if (LocationID != value.ID)
                        {
                            throw new InvalidOperationException("The principal end of an identifying relationship can only be changed when the dependent end is in the Added state.");
                        }
                    }
                    var previousValue = _archive;
                    _archive = value;
                    FixupArchive(previousValue);
                    OnNavigationPropertyChanged("Archive");
                }
            }
        }
        private Archive _archive;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        // This entity type is the dependent end in at least one association that performs cascade deletes.
        // This event handler will process notifications that occur when the principal end is deleted.
        internal void HandleCascadeDelete(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                this.MarkAsDeleted();
            }
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Photo = null;
            Archive = null;
        }

        #endregion
        #region Association Fixup
    
        private void FixupPhoto(Photo previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.Photos2Locations.Contains(this))
            {
                previousValue.Photos2Locations.Remove(this);
            }
    
            if (Photo != null)
            {
                if (!Photo.Photos2Locations.Contains(this))
                {
                    Photo.Photos2Locations.Add(this);
                }
    
                PhotoID = Photo.ID;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Photo")
                    && (ChangeTracker.OriginalValues["Photo"] == Photo))
                {
                    ChangeTracker.OriginalValues.Remove("Photo");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Photo", previousValue);
                }
                if (Photo != null && !Photo.ChangeTracker.ChangeTrackingEnabled)
                {
                    Photo.StartTracking();
                }
            }
        }
    
        private void FixupArchive(Archive previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.Photos2Locations.Contains(this))
            {
                previousValue.Photos2Locations.Remove(this);
            }
    
            if (Archive != null)
            {
                if (!Archive.Photos2Locations.Contains(this))
                {
                    Archive.Photos2Locations.Add(this);
                }
    
                LocationID = Archive.ID;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Archive")
                    && (ChangeTracker.OriginalValues["Archive"] == Archive))
                {
                    ChangeTracker.OriginalValues.Remove("Archive");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Archive", previousValue);
                }
                if (Archive != null && !Archive.ChangeTracker.ChangeTrackingEnabled)
                {
                    Archive.StartTracking();
                }
            }
        }

        #endregion
    }
}
