//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace WpfKolekcjaZdjec.Entities
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class WpfKolekcjaZdjecEntitiesDataModelContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new WpfKolekcjaZdjecEntitiesDataModelContainer object using the connection string found in the 'WpfKolekcjaZdjecEntitiesDataModelContainer' section of the application configuration file.
        /// </summary>
        public WpfKolekcjaZdjecEntitiesDataModelContainer() : base("name=WpfKolekcjaZdjecEntitiesDataModelContainer", "WpfKolekcjaZdjecEntitiesDataModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new WpfKolekcjaZdjecEntitiesDataModelContainer object.
        /// </summary>
        public WpfKolekcjaZdjecEntitiesDataModelContainer(string connectionString) : base(connectionString, "WpfKolekcjaZdjecEntitiesDataModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new WpfKolekcjaZdjecEntitiesDataModelContainer object.
        /// </summary>
        public WpfKolekcjaZdjecEntitiesDataModelContainer(EntityConnection connection) : base(connection, "WpfKolekcjaZdjecEntitiesDataModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
    }
    

    #endregion
    
    
}
